sudo: false
language: node_js
node_js:
    - "node"
cache:
    directories:
        - "node_modules"
env:
    global:
        secure: ""
    matrix:
        - FX_VERSION="54.0b"
        - FX_VERSION="45.0.2esr"
matrix:
    fast_finish: true
    #allow_failures:
    #    - env: FX_CHANNEL="beta"
notifications:
    email: false
install:
    - if [ $FX_VERSION = "45.0.2esr" ]; then
        wget -O tarball "https://archive.mozilla.org/pub/firefox/releases/45.0.2esr/linux-x86_64/en-US/firefox-45.0.2esr.tar.bz2";
      fi
    - if [ $FX_VERSION = "54.0b" ]; then
        wget -O tarball "https://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-beta-linux64-add-on-devel/1496339244/firefox-54.0.en-US.linux-x86_64-add-on-devel.tar.bz2";
      fi
    - tar xf tarball
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm i
    - node_modules/.bin/gulp build
    - if [ $FX_VERSION = "54.0b" ] &&
         [ $TRAVIS_REPO_SLUG = "zotero/zotero" ] &&
         [ $TRAVIS_BRANCH = "master" ] &&
         [ $TRAVIS_PULL_REQUEST = "false" ]; then
        mkdir build-zip;
        cd build;
        zip -r ../build-zip/$TRAVIS_COMMIT.zip *;
        cd ..;
        gem install dpl;
        dpl --provider=s3
            --access-key-id=AKIAJFDVJ54MCAEXPQ5Q
            --bucket=zotero-download
            --local-dir=build-zip
            --upload-dir=ci/client
            --acl=public-read
            --skip_cleanup=true;
      fi
    - unset AWS_SECRET_ACCESS_KEY
script:
    - test/runtests.sh -x firefox/firefox
