sudo: false
language: cpp
compiler:
    - gcc
env:
    - FX_CHANNEL=""
    - FX_CHANNEL="-esr"
    # Disabled until unbranded build is available
    #- FX_CHANNEL="-beta"
matrix:
    fast_finish: true
    allow_failures:
        - env: FX_CHANNEL="-beta"
notifications:
    email: false
install:
    - wget -O tarball "https://download.mozilla.org/?product=firefox${FX_CHANNEL}-latest&os=linux64&lang=en-US"
    - tar xf tarball
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
script:
    - test/runtests.sh -x firefox/firefox
